language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: oaf4xa9OfFxMKQ1dWPEqfv4uHzVemDolDfxeP7jU70GTLNPUYS/uaEOVE3ZOVKiblkAe51sfxw1sdkAWdT/FBAA7UWR/Su4yO4Q1JRF+oWRwEoi9AcaMwlQcdeD4kmYJCC95+Qwg/PUo+z8fVdV45E/g0TWvqpv8L3FQYt9mafo=
  - secure: HxipQEtL+qGE0VsBBLr/v7uFaN14Se38B5+qsJmgmTC744FuxYmOjF9mmsYUEsGusv0dg+IBJJ7B8PqnwHLG+d+vGJ8xYuPbQa0o8ZvFDoKtlfDnqele1vMR0hPRj8JG415pzAKEC6LDNLhFhUt9wxuLz6AUoJWLl3bmDoXdhoI=
  - secure: eDLT0yy/KeIVzwDZO3PVmrNbSw+ak2/L2if8NagYkoUsM/0G7nwdQe/7PeqeMEP9xujkitc4s4q8A0QtLSj5611IubEWDlGmaarOfbXZhw07Kp7kLXQ5krQtiAxobNtM4X92n+tx8lCjlvW5cZuXyri1HvjhHteT/YdXP68YeWI=
  - secure: JLghtw2lN+lZTcJy0GtUvpeWPOy6vss19DalPM2eILFgY20VHzNAEhQHr3IA60m7Fw/cKICRzuBkSBET+CFmc2lLN+l8Kdu+vKd/ikMLzD0TUueQEClwRarF9aJKyNCPL/sn0UM0/r8M8rt8cmiMJqbCsym69LwwjB3aafxddYg=
